// Generated by https://quicktype.io

export interface UserProfile {
  country:       string;
  display_name:  string;
  email:         string;
  external_urls: ExternalUrls;
  followers:     Followers;
  href:          string;
  id:            string;
  images:        Image[];
  product:       string;
  type:          string;
  uri:           string;
}

export interface ExternalUrls {
  spotify: string;
}

export interface Followers {
  href:  null;
  total: number;
}

export interface Image {
  height: null;
  url:    string;
  width:  null;
}
